//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IconPacks.Browser.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("280")]
        public double SidebarExpandedWidth {
            get {
                return ((double)(this["SidebarExpandedWidth"]));
            }
            set {
                this["SidebarExpandedWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("48")]
        public double IconPreviewSize {
            get {
                return ((double)(this["IconPreviewSize"]));
            }
            set {
                this["IconPreviewSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.Color IconForeground {
            get {
                return ((global::System.Windows.Media.Color)(this["IconForeground"]));
            }
            set {
                this["IconForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public global::System.Windows.Media.Color IconBackground {
            get {
                return ((global::System.Windows.Media.Color)(this["IconBackground"]));
            }
            set {
                this["IconBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF008A00")]
        public global::System.Windows.Media.Color AppAccentColor {
            get {
                return ((global::System.Windows.Media.Color)(this["AppAccentColor"]));
            }
            set {
                this["AppAccentColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Light")]
        public string AppTheme {
            get {
                return ((string)(this["AppTheme"]));
            }
            set {
                this["AppTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExportTemplatesDir {
            get {
                return ((string)(this["ExportTemplatesDir"]));
            }
            set {
                this["ExportTemplatesDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00FFFFFF")]
        public global::System.Windows.Media.Color IcoExportIconBackground {
            get {
                return ((global::System.Windows.Media.Color)(this["IcoExportIconBackground"]));
            }
            set {
                this["IcoExportIconBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.Color IcoExportIconForeground {
            get {
                return ((global::System.Windows.Media.Color)(this["IcoExportIconForeground"]));
            }
            set {
                this["IcoExportIconForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public global::System.Windows.Media.Color IcoExportPathFill {
            get {
                return ((global::System.Windows.Media.Color)(this["IcoExportPathFill"]));
            }
            set {
                this["IcoExportPathFill"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.Color IcoExportPathStroke {
            get {
                return ((global::System.Windows.Media.Color)(this["IcoExportPathStroke"]));
            }
            set {
                this["IcoExportPathStroke"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("256")]
        public int IcoExportIconSize {
            get {
                return ((int)(this["IcoExportIconSize"]));
            }
            set {
                this["IcoExportIconSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("256")]
        public int IcoExportRectSize {
            get {
                return ((int)(this["IcoExportRectSize"]));
            }
            set {
                this["IcoExportRectSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int IcoExportRectRadius {
            get {
                return ((int)(this["IcoExportRectRadius"]));
            }
            set {
                this["IcoExportRectRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int IcoExportPathStrokeThickness {
            get {
                return ((int)(this["IcoExportPathStrokeThickness"]));
            }
            set {
                this["IcoExportPathStrokeThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IcoExportRectEnabled {
            get {
                return ((bool)(this["IcoExportRectEnabled"]));
            }
            set {
                this["IcoExportRectEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int IcoExportIconRotate {
            get {
                return ((int)(this["IcoExportIconRotate"]));
            }
            set {
                this["IcoExportIconRotate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int IcoExportIconTranslateX {
            get {
                return ((int)(this["IcoExportIconTranslateX"]));
            }
            set {
                this["IcoExportIconTranslateX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int IcoExportIconTranslateY {
            get {
                return ((int)(this["IcoExportIconTranslateY"]));
            }
            set {
                this["IcoExportIconTranslateY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IcoExport16 {
            get {
                return ((bool)(this["IcoExport16"]));
            }
            set {
                this["IcoExport16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IcoExport24 {
            get {
                return ((bool)(this["IcoExport24"]));
            }
            set {
                this["IcoExport24"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IcoExport32 {
            get {
                return ((bool)(this["IcoExport32"]));
            }
            set {
                this["IcoExport32"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IcoExport48 {
            get {
                return ((bool)(this["IcoExport48"]));
            }
            set {
                this["IcoExport48"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IcoExport64 {
            get {
                return ((bool)(this["IcoExport64"]));
            }
            set {
                this["IcoExport64"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IcoExport72 {
            get {
                return ((bool)(this["IcoExport72"]));
            }
            set {
                this["IcoExport72"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IcoExport96 {
            get {
                return ((bool)(this["IcoExport96"]));
            }
            set {
                this["IcoExport96"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IcoExport128 {
            get {
                return ((bool)(this["IcoExport128"]));
            }
            set {
                this["IcoExport128"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IcoExport180 {
            get {
                return ((bool)(this["IcoExport180"]));
            }
            set {
                this["IcoExport180"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IcoExport256 {
            get {
                return ((bool)(this["IcoExport256"]));
            }
            set {
                this["IcoExport256"] = value;
            }
        }
    }
}
